---
kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: build
    image: plugins/kaniko
    settings:
      repo: giosg/k8s-hello-world
      tags:
        - latest
        - ${DRONE_COMMIT}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
