---
kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: test
    image: python:3.7
    commands:
      - pip install -r requirements.txt
      - python -m unittest test/test_api.py
    environment:
      REDIS_URL: redis://redis:6379/0

  - name: build
    image: plugins/kaniko
    settings:
      repo: giosg/k8s-hello-world
      tags:
        - latest
        - ${DRONE_COMMIT}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch:
        - main

services:
  - name: redis
    image: redis
    ports:
      - 6379
