---
kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: build
    image: plugins/kaniko
    settings:
      repo: giosg/k8s-hello-world
      tags:
        - latest
        - ${DRONE_COMMIT}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: deploy
    image: giosg/drone-helm:test-v3
    settings:
      chart: charts/hello-world
      namespace: default
      release_name: example
      values:
        - imageTag=${DRONE_COMMIT}
        - changecause=${DRONE_COMMIT}
      api_server:
        from_secret: k8s-sb-server
      kubernetes_token:
        from_secret: k8s-token
      set_value_template:
        - "replicas=1"
  
